# **DPP-4**

In [ ]:
import pandas as pd
df=pd.read_csv('/save.csv')
df.head(15)

    S No.            Name Class  Roll No.  Marks
0       1    Aarav Sharma   10A      1001     78
1       2     Priya Singh   10B      1002     92
2       3     Rohan Verma    9A      1003     65
3       4    Ananya Gupta    9B      1004     88
4       5     Kunal Mehta   10A      1005     74
5       6     Sneha Patel    8A      1006     95
6       7    Aditya Kumar    8B      1007     81
7       8      Neha Joshi    9A      1008     69
8       9       Vivek Rao   10B      1009     85
9      10     Isha Kapoor    8A      1010     90
10     11      Arjun Nair    9B      1011     72
11     12       Pooja Das   10A      1012     87
12     13     Rahul Yadav    8B      1013     63
13     14    Meera Chawla    9A      1014     94
14     15  Siddharth Jain   10B      1015     79

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15 entries, 0 to 14
Data columns (total 5 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   S No.     15 non-null     int64
 1   Name      15 non-null     object
 2   Class     15 non-null     object
 3   Roll No.  15 non-null     int64
 4   Marks     15 non-null     int64
dtypes: int64(3), object(2)
memory usage: 732.0+ bytes

In [ ]:
import pandas as pd
data=[100,200,300,400]
base= pd.Series(data)
print(base)

0    100
1    200
2    300
3    400
dtype: int64

In [ ]:
user_dict={'namae':["alice","bob","charile","kavya","khushi","prachi"],'Age':[25,30,35,18,19,19]}
df=pd.DataFrame(user_dict)
print(df)

     namae  Age
0    alice   25
1      bob   30
2  charile   35
3    kavya   18
4   khushi   19
5   prachi   19

In [ ]:
df.head(5
      )

     namae  Age
0    alice   25
1      bob   30
2  charile   35
3    kavya   18
4   khushi   19

In [ ]:
print(df.shape)

(6, 2)

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   namae   6 non-null      object
 1   Age     6 non-null      int64
dtypes: int64(1), object(1)
memory usage: 228.0+ bytes

In [ ]:
df1=pd.DataFrame({"product":["vase","top","cake","notebook","mouse"],"price":[2000,1200,500,130,1200],"quantity":[20,25,15,50,18]})
print(df1)

    product  price  quantity
0      vase   2000        20
1       top   1200        25
2      cake    500        15
3  notebook    130        50
4     mouse   1200        18

In [ ]:
df1["price"]

0    2000
1    1200
2     500
3     130
4    1200
Name: price, dtype: int64

In [ ]:
df2=pd.DataFrame(df1[df1['price']>1000])

In [ ]:
print(df2)

  product  price  quantity
0    vase   2000        20
1     top   1200        25
4   mouse   1200        18

In [ ]:
df2.min()

product     mouse
price        1200
quantity       18
dtype: object

In [ ]:
df2.max()

product     vase
price       2000
quantity      25
dtype: object

In [ ]:
df2['price'].mean()

np.float64(1466.6666666666667)

In [ ]:
df2['price'].std()

461.8802153517006

In [ ]:
import scipy.constants as sconst
print(sconst.pi)

3.141592653589793

In [ ]:
sconst.Planck

6.62607015e-34

In [ ]:
sconst.c

299792458.0

In [ ]:

miles=55
pound=10
meter=miles*sconst.mile
kg=pound*sconst.pound

In [ ]:
meter

88513.91999999998

In [ ]:
kg

4.5359237

In [ ]:
import numpy as np
arr=np.array([1,8,27,64])
import scipy.special as sps
sps.c_roots(len(arr))

(array([-1.84775907, -0.76536686,  0.76536686,  1.84775907]),
 array([1.57079633, 1.57079633, 1.57079633, 1.57079633]))

In [ ]:
c_arr = np.cbrt(arr)
print(c_arr)

[1. 2. 3. 4.]

In [ ]:
dataset=[1,2,2,3,4,4,45,6]
import scipy.stats as sps
sps.mode(dataset)

ModeResult(mode=np.int64(2), count=np.int64(2))

In [ ]:
ar=[2,8,32]
sps.gmean(ar)

np.float64(7.999999999999998)

In [ ]:
m=np.array([[4,5],[2,3]])
import scipy.linalg as slg
slg.det(m)

np.float64(2.0000000000000018)

In [ ]:
m=np.array([[1,2],[3,4]])
import scipy.linalg as slg
slg.inv(m)

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [ ]:
import scipy.stats as sps
sps.

In [ ]:
df=pd.read_csv('/save2.csv')

In [ ]:
df.fillna("null")

    S No.            Name Class Roll No. Marks
0       1    Aarav Sharma   10A   1001.0  78.0
1       2     Priya Singh   10B   1002.0  92.0
2       3     Rohan Verma    9A   1003.0  65.0
3       4            null    9B   1004.0  88.0
4       5     Kunal Mehta   10A   1005.0  74.0
5       6     Sneha Patel    8A   1006.0  95.0
6       7    Aditya Kumar    8B     null  81.0
7       8      Neha Joshi    9A   1008.0  69.0
8       9       Vivek Rao   10B   1009.0  85.0
9      10     Isha Kapoor    8A   1010.0  90.0
10     11      Arjun Nair    9B   1011.0  72.0
11     12       Pooja Das   10A   1012.0  87.0
12     13     Rahul Yadav    8B   1013.0  null
13     14    Meera Chawla    9A   1014.0  94.0
14     15  Siddharth Jain   10B   1015.0  79.0

In [ ]:
import scipy.stats as st
df3=pd.DataFrame({"score":[20,81,66,88,77,91,95,45,61]})
st.percentileofscore(df3["score"], 75)

np.float64(44.44444444444444)

In [ ]:
st.zscore(df3["score"])

array([-2.14110834,  0.50634319, -0.14466948,  0.8101491 ,  0.33273981,
        0.94035163,  1.11395501, -1.05608722, -0.36167371])

In [ ]:
from scipy.optimize import minimize_scalar
def f(x):
  return x**2+10 * np.sin(x)

print(f(2))

13.092974268256818