# **DPP-5**

In [ ]:
import pandas as pd
df={"studyhours":[2,3,4,5,6,7],"Marks":[40,50,60,70,80,90]}
df=pd.DataFrame(df)
print(df)

   studyhours  Marks
0           2     40
1           3     50
2           4     60
3           5     70
4           6     80
5           7     90

In [ ]:
x=df[["studyhours"]]
y=df[["Marks"]]
from sklearn.linear_model import LinearRegression
model=LinearRegression()
model.fit(x,y)
prediction=model.predict([[8]])
print(prediction)
print(model)

[[100.]]
LinearRegression()

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

In [ ]:
df=pd.read_csv('/content/Student.csv')

In [ ]:
df=pd.DataFrame(df)
df

    StudentID     Name  Gender  Age Department  Marks  Attendance     city
0         101     Amit    Male   20        CSE   85.0        92.0    Delhi
1         102    Priya  Female   21        CSE   78.0        88.0   Mumbai
2         103    Rahul    Male   22        ECE   90.0        95.0    Delhi
3         104     Neha  Female   20        ECE   67.0        75.0   Jaipur
4         105    Mohit    Male   21        CSE   82.0        89.0    Delhi
5         106   Anjali  Female   22         ME   91.0        96.0  Lukhnow
6         107    Rohan    Male   20         ME   73.0        80.0   Jaipur
7         108  Simaran  Female   21        CSE   88.0        94.0   Mumbai
8         109    Arjun    Male   22        ECE   79.0        85.0    Delhi
9         110    Pooja  Female   20         ME   86.0        91.0  Lukhnow
10        111    Karan    Male   21        CSE    NaN        87.0    Delhi
11        112    Sneha  Female   20        ECE   84.0         NaN   Mumbai

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12 entries, 0 to 11
Data columns (total 8 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   StudentID   12 non-null     int64
 1   Name        12 non-null     object
 2   Gender      12 non-null     object
 3   Age         12 non-null     int64
 4   Department  12 non-null     object
 5   Marks       11 non-null     float64
 6   Attendance  11 non-null     float64
 7   city        12 non-null     object
dtypes: float64(2), int64(2), object(4)
memory usage: 900.0+ bytes

In [ ]:
df.isnull().sum()

StudentID     0
Name          0
Gender        0
Age           0
Department    0
Marks         1
Attendance    1
city          0
dtype: int64

In [ ]:
df['Marks'] = df['Marks'].fillna(df['Marks'].mean())

In [ ]:
df['Attendance']=df['Attendance'].fillna(df['Attendance'].mean())

In [ ]:
print (df)

    StudentID     Name  Gender  Age Department      Marks  Attendance     city
0         101     Amit    Male   20        CSE  85.000000   92.000000    Delhi
1         102    Priya  Female   21        CSE  78.000000   88.000000   Mumbai
2         103    Rahul    Male   22        ECE  90.000000   95.000000    Delhi
3         104     Neha  Female   20        ECE  67.000000   75.000000   Jaipur
4         105    Mohit    Male   21        CSE  82.000000   89.000000    Delhi
5         106   Anjali  Female   22         ME  91.000000   96.000000  Lukhnow
6         107    Rohan    Male   20         ME  73.000000   80.000000   Jaipur
7         108  Simaran  Female   21        CSE  88.000000   94.000000   Mumbai
8         109    Arjun    Male   22        ECE  79.000000   85.000000    Delhi
9         110    Pooja  Female   20         ME  86.000000   91.000000  Lukhnow
10        111    Karan    Male   21        CSE  82.090909   87.000000    Delhi
11        112    Sneha  Female   20        ECE  84.000000   88.363636   Mumbai

In [ ]:
df=df.drop('Name',axis=1)
print(df)

    StudentID  Gender  Age Department      Marks  Attendance     city
0         101    Male   20        CSE  85.000000   92.000000    Delhi
1         102  Female   21        CSE  78.000000   88.000000   Mumbai
2         103    Male   22        ECE  90.000000   95.000000    Delhi
3         104  Female   20        ECE  67.000000   75.000000   Jaipur
4         105    Male   21        CSE  82.000000   89.000000    Delhi
5         106  Female   22         ME  91.000000   96.000000  Lukhnow
6         107    Male   20         ME  73.000000   80.000000   Jaipur
7         108  Female   21        CSE  88.000000   94.000000   Mumbai
8         109    Male   22        ECE  79.000000   85.000000    Delhi
9         110  Female   20         ME  86.000000   91.000000  Lukhnow
10        111    Male   21        CSE  82.090909   87.000000    Delhi
11        112  Female   20        ECE  84.000000   88.363636   Mumbai

In [ ]:
from sklearn.linear_model import LinearRegression
x=df[['Attendance']]
y=df[['Marks']]
model=LinearRegression()
model.fit(x,y)
prediction=model.predict([[92]])
print(prediction)
print(model)

[[86.14363427]]
LinearRegression()

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(